name: "CI :: Monorepo (full)"

on:
  push:
    branches: [main]
  pull_request:
    branches: "**"

concurrency:
  group: ${{ github.event.pull_request && format('monorepo-pr-ci-full-{0}', github.event.pull_request.number) || 'monorepo-pr-ci-full-push-main' }}
  cancel-in-progress: true

jobs:
  monorepo-pr-ci-full:
    if: github.event.pull_request.draft == false
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Support longpaths"
        if: matrix.os == 'windows-latest'
        run: git config --system core.longpaths true

      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.base_ref }}

      - name: "Setup kie-tools-bot"
        uses: ./.github/actions/setup-kie-tools-bot

      - name: "Merge PR changes"
        uses: ./.github/actions/merge-pr-changes

      - name: "Check if should run or not"
        id: check_diff_paths
        shell: bash
        run: |
          # If there are no changed files outside `packages` or `examples`,
          # we don't need to run the full CI.

          read -r -a PATHS <<< $(git diff --name-only ${{ github.base_ref }} ${{ github.head_ref }} -- ':!packages' ':!examples')

          if [ ${#PATHS[@]} -eq 0 ]; then
            echo '`CI` is already running, no need to run this one.'
            echo "::set-output name=should_run::false"
          else
            echo "::set-output name=should_run::true"
          fi

      - name: "Setup environment"
        if: steps.check_diff_paths.should_run
        uses: ./.github/actions/setup-env
        with:
          os: ${{ matrix.os }}

      - name: "Build"
        if: steps.check_diff_paths.should_run
        env:
          WEBPACK__minimize: "false"
          WEBPACK__tsLoaderTranspileOnly: "false"
          KIE_TOOLS_BUILD_lint: "true"
          KIE_TOOLS_BUILD_test: "true"
          KIE_TOOLS_BUILD_testIT: ${{ matrix.os == 'ubuntu-latest' }}
          KIE_TOOLS_BUILD_docker: "true"
          KIE_TOOLS_BUILD_examples: "true"
          DISPLAY: ":99.0"
          START_SERVER_AND_TEST_INSECURE: "true"
        run: |
          lerna run build:prod --stream --concurrency 1

      - name: "Check generated resources (you should commit those!)"
        if: steps.check_diff_paths.should_run
        shell: bash
        run: |
          git diff
          [ "0" == "$(git diff | wc -l | tr -d ' ')" ]

      - name: "Upload build artifacts"
        uses: actions/upload-artifact@v2
        if: always() && !cancelled() && check_diff_paths.should_run
        with:
          name: artifacts-${{ matrix.os }}
          if-no-files-found: warn
          path: |
            packages/*/dist
            packages/desktop/out/*.zip
            !packages/desktop/dist

      - name: "Upload IT Tests artifacts"
        uses: actions/upload-artifact@v2
        if: always() && !cancelled() && check_diff_paths.should_run
        with:
          name: it-tests-artifacts-${{ matrix.os }}
          if-no-files-found: warn
          path: |
            packages/*/dist-it-tests
